"""
Test script for pyaermod output parser

Creates a sample AERMOD output file and demonstrates parsing capabilities.
"""

from pyaermod_output_parser import parse_aermod_output, AERMODResults
import pandas as pd
import numpy as np
from pathlib import Path


def create_sample_output_file(filename: str = "sample_aermod.out"):
    """
    Create a sample AERMOD output file for testing

    This mimics the format of actual AERMOD output files.
    """

    content = """
*** AERMOD - VERSION  24142 ***   *** Jobname: Sample_AERMOD_Run                ***

        ***** SETUP Finishes Successfully *****


 *** AERMOD - VERSION  24142 ***   *** Sample AERMOD Run                        ***
                                    *** Generated by pyaermod                    ***

                *** THE BASIC SETUP INFORMATION ***
               *** FROM THE AERMOD INPUT RUNSTREAM ***


  --  MODELING OPTIONS SELECTED:

       CONC -- Concentration Calculation
       FLAT -- Flat Terrain

 *** MODEL SETUP OPTIONS  ***

       Pollutant/Gas ID:  PM25
       Averaging Time Period(s):  ANNUAL 24-HOUR 1-HOUR


 *** MODELING PERIOD ***

   STARTING DATE:  01/01/23
   ENDING DATE:    12/31/23


 *** SOURCE LOCATIONS ***

   SOURCE    TYPE      X-COORD       Y-COORD    BASE ELEV.  STACK HT  STACK TEMP EXIT VEL  DIAMETER  EMIS RATE
   STACK1    POINT       500.00       500.00        10.00     50.00      400.00    15.00      2.00      1.50


 *** RECEPTOR LOCATIONS ***

   X-COORD       Y-COORD      ZELEV     ZHILL     ZFLAG
      0.00         0.00       0.00      0.00      0.00
    100.00         0.00       0.00      0.00      0.00
    200.00         0.00       0.00      0.00      0.00
    300.00         0.00       0.00      0.00      0.00
    400.00         0.00       0.00      0.00      0.00
    500.00         0.00       0.00      0.00      0.00
    600.00         0.00       0.00      0.00      0.00
      0.00       100.00       0.00      0.00      0.00
    100.00       100.00       0.00      0.00      0.00
    200.00       100.00       0.00      0.00      0.00


 *** ANNUAL RESULTS ***

   X-COORD       Y-COORD    CONC (UG/M3)
      0.00         0.00         3.2145
    100.00         0.00         5.8234
    200.00         0.00         8.1245
    300.00         0.00        12.4567
    400.00         0.00        15.2341
    500.00         0.00        18.9876
    600.00         0.00        14.3421
      0.00       100.00         4.1234
    100.00       100.00         6.7823
    200.00       100.00         9.5432


 *** 24-HOUR RESULTS (High 1st-High Value) ***

   X-COORD       Y-COORD    CONC (UG/M3)
      0.00         0.00        15.2341
    100.00         0.00        28.4123
    200.00         0.00        35.6789
    300.00         0.00        48.2341
    400.00         0.00        52.8901
    500.00         0.00        58.3456
    600.00         0.00        45.2314
      0.00       100.00        18.9234
    100.00       100.00        32.1245
    200.00       100.00        41.2345


 *** 1-HOUR RESULTS (High 1st-High Value) ***

   X-COORD       Y-COORD    CONC (UG/M3)
      0.00         0.00        85.2341
    100.00         0.00       145.6789
    200.00         0.00       198.3456
    300.00         0.00       256.7890
    400.00         0.00       285.4321
    500.00         0.00       312.8765
    600.00         0.00       267.4532
      0.00       100.00       102.3456
    100.00       100.00       178.9012
    200.00       100.00       223.4567


 *** OVERALL MAXIMUM VALUES ***

 ANNUAL:    Maximum = 18.9876 at (  500.00,    0.00)
 24-HOUR:   Maximum = 58.3456 at (  500.00,    0.00)
 1-HOUR:    Maximum = 312.8765 at ( 500.00,    0.00)

        ***** The AERMOD Run Finishes Successfully *****
"""

    with open(filename, 'w') as f:
        f.write(content)

    return filename


def test_basic_parsing():
    """Test 1: Basic parsing of AERMOD output"""
    print("=" * 70)
    print("TEST 1: Basic Output Parsing")
    print("=" * 70)

    # Create sample output
    output_file = create_sample_output_file("test1_output.out")
    print(f"Created sample output file: {output_file}\n")

    # Parse it
    results = parse_aermod_output(output_file)

    # Display summary
    print(results.summary())
    print()


def test_concentration_extraction():
    """Test 2: Extract concentration DataFrames"""
    print("=" * 70)
    print("TEST 2: Concentration Data Extraction")
    print("=" * 70)

    output_file = "test1_output.out"
    results = parse_aermod_output(output_file)

    # Get annual concentrations
    annual_df = results.get_concentrations('ANNUAL')
    print("Annual Concentrations DataFrame:")
    print(annual_df)
    print()

    # Get 24-hour concentrations
    hr24_df = results.get_concentrations('24HR')
    print("24-Hour Concentrations DataFrame:")
    print(hr24_df)
    print()

    # Get 1-hour concentrations
    hr1_df = results.get_concentrations('1HR')
    print("1-Hour Concentrations DataFrame (first 5):")
    print(hr1_df.head())
    print()


def test_max_values():
    """Test 3: Extract maximum values"""
    print("=" * 70)
    print("TEST 3: Maximum Value Extraction")
    print("=" * 70)

    output_file = "test1_output.out"
    results = parse_aermod_output(output_file)

    # Get max for each averaging period
    for period in ['ANNUAL', '24HR', '1HR']:
        max_info = results.get_max_concentration(period)
        print(f"{period}:")
        print(f"  Maximum concentration: {max_info['value']:.4f} {max_info['units']}")
        print(f"  Location: ({max_info['x']:.2f}, {max_info['y']:.2f})")
        print()


def test_point_lookup():
    """Test 4: Look up concentration at specific points"""
    print("=" * 70)
    print("TEST 4: Point Concentration Lookup")
    print("=" * 70)

    output_file = "test1_output.out"
    results = parse_aermod_output(output_file)

    # Look up concentrations at specific points
    test_points = [
        (500.0, 0.0),
        (100.0, 100.0),
        (200.0, 0.0)
    ]

    print("Annual concentrations at test points:")
    for x, y in test_points:
        conc = results.get_concentration_at_point(x, y, 'ANNUAL', tolerance=1.0)
        if conc is not None:
            print(f"  ({x:6.1f}, {y:6.1f}): {conc:8.4f} ug/m^3")
        else:
            print(f"  ({x:6.1f}, {y:6.1f}): No receptor found")
    print()


def test_dataframe_exports():
    """Test 5: Export to DataFrames"""
    print("=" * 70)
    print("TEST 5: DataFrame Exports")
    print("=" * 70)

    output_file = "test1_output.out"
    results = parse_aermod_output(output_file)

    # Export sources
    sources_df = results.get_sources_dataframe()
    print("Sources DataFrame:")
    print(sources_df)
    print()

    # Export receptors
    receptors_df = results.get_receptors_dataframe()
    print(f"Receptors DataFrame (showing first 5 of {len(receptors_df)}):")
    print(receptors_df.head())
    print()


def test_csv_export():
    """Test 6: Export to CSV files"""
    print("=" * 70)
    print("TEST 6: CSV File Export")
    print("=" * 70)

    output_file = "test1_output.out"
    results = parse_aermod_output(output_file)

    # Export to CSV
    output_dir = "aermod_results"
    results.export_to_csv(output_dir, prefix="test_run")

    print(f"\nCSV files created in '{output_dir}/':")

    # List created files
    output_path = Path(output_dir)
    if output_path.exists():
        for csv_file in sorted(output_path.glob("*.csv")):
            size_kb = csv_file.stat().st_size / 1024
            print(f"  - {csv_file.name} ({size_kb:.1f} KB)")
    print()


def test_statistical_analysis():
    """Test 7: Basic statistical analysis"""
    print("=" * 70)
    print("TEST 7: Statistical Analysis")
    print("=" * 70)

    output_file = "test1_output.out"
    results = parse_aermod_output(output_file)

    # Analyze annual concentrations
    annual_df = results.get_concentrations('ANNUAL')

    print("Annual Concentration Statistics:")
    print(f"  Mean:       {annual_df['concentration'].mean():.4f} ug/m^3")
    print(f"  Median:     {annual_df['concentration'].median():.4f} ug/m^3")
    print(f"  Std Dev:    {annual_df['concentration'].std():.4f} ug/m^3")
    print(f"  Min:        {annual_df['concentration'].min():.4f} ug/m^3")
    print(f"  Max:        {annual_df['concentration'].max():.4f} ug/m^3")
    print()

    # Percentiles
    print("Percentiles:")
    for p in [25, 50, 75, 90, 95, 99]:
        val = annual_df['concentration'].quantile(p/100)
        print(f"  {p:3d}th:      {val:.4f} ug/m^3")
    print()


def test_compliance_checking():
    """Test 8: Compliance checking example"""
    print("=" * 70)
    print("TEST 8: Regulatory Compliance Check")
    print("=" * 70)

    output_file = "test1_output.out"
    results = parse_aermod_output(output_file)

    # Example NAAQS standards (hypothetical)
    standards = {
        'ANNUAL': 12.0,  # Annual PM2.5 standard
        '24HR': 35.0,    # 24-hour PM2.5 standard
        '1HR': 300.0     # Example 1-hour standard
    }

    print("Compliance Check (PM2.5 Standards):\n")

    for period, standard in standards.items():
        if period in results.concentrations:
            max_info = results.get_max_concentration(period)
            max_conc = max_info['value']

            exceeds = max_conc > standard
            status = "EXCEEDS" if exceeds else "COMPLIES"
            pct = (max_conc / standard) * 100

            print(f"{period}:")
            print(f"  Standard:    {standard:.2f} ug/m^3")
            print(f"  Maximum:     {max_conc:.2f} ug/m^3")
            print(f"  Percentage:  {pct:.1f}% of standard")
            print(f"  Status:      {status}")
            print()


def run_all_tests():
    """Run all test cases"""

    tests = [
        ("Basic Parsing", test_basic_parsing),
        ("Concentration Extraction", test_concentration_extraction),
        ("Maximum Values", test_max_values),
        ("Point Lookup", test_point_lookup),
        ("DataFrame Exports", test_dataframe_exports),
        ("CSV Export", test_csv_export),
        ("Statistical Analysis", test_statistical_analysis),
        ("Compliance Checking", test_compliance_checking)
    ]

    for name, test_func in tests:
        try:
            test_func()
        except Exception as e:
            print(f"ERROR in {name}: {e}")
            print()

    print("=" * 70)
    print("ALL TESTS COMPLETED")
    print("=" * 70)
    print("\nOutput parser ready for use!")
    print("\nNext steps:")
    print("  1. Run AERMOD with generated input files")
    print("  2. Parse the output with pyaermod_output_parser")
    print("  3. Analyze results in Python/pandas")
    print("  4. Create visualizations (coming next!)")


if __name__ == "__main__":
    run_all_tests()
