#!/usr/bin/env python3
"""
Generate a Markdown parity report against the EPA AERMOD test-case suite.

Runs every input deck in ``test_cases/aermet_24142_aermod_24142/inputs/``
through the local AERMOD binary, scores each produced POSTFILE against
the EPA reference of the same name, and writes a per-case results table
to stdout (or to ``--output`` if specified).

Pass criterion: best-fit slope within ±0.001 of 1.0, matching EPA's own
``Compare_AERMOD_test_cases.R`` margin.

Usage::

    python scripts/run_epa_parity.py
    python scripts/run_epa_parity.py --output docs/validation.md
    python scripts/run_epa_parity.py --filter aertest

Skips MULTYEAR-chained decks (run via the dedicated chained test).
"""

from __future__ import annotations

import argparse
import shutil
import sys
import time
from pathlib import Path
from typing import List

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))

from pyaermod.regulatory_parity import (  # noqa: E402
    DEFAULT_SLOPE_TOLERANCE,
    ParityScore,
    score_postfile_pair,
)
from pyaermod.runner import AERMODRunner  # noqa: E402

EPA_DIR = ROOT / "test_cases" / "aermet_24142_aermod_24142"
INPUTS = EPA_DIR / "inputs"
MET = EPA_DIR / "meteorology"
REF_PST = EPA_DIR / "postfiles"


def _stage_workdir(work: Path, deck_name: str) -> Path:
    """Stage inputs + met data so relative paths in the deck resolve."""
    for sub in ("inputs", "meteorology", "postfiles", "plotfiles", "Outputs"):
        (work / sub).mkdir(parents=True, exist_ok=True)
    shutil.copy2(INPUTS / deck_name, work / "inputs" / deck_name)
    for f in INPUTS.iterdir():
        if f.is_file() and f.suffix.lower() != ".inp":
            shutil.copy2(f, work / "inputs" / f.name)
    for f in MET.iterdir():
        if f.is_file():
            shutil.copy2(f, work / "meteorology" / f.name)
    return work / "inputs"


def _run_one(deck_name: str, scratch: Path,
             runner: AERMODRunner) -> List[ParityScore]:
    """Run one deck and return parity scores for each PST emitted."""
    work = scratch / deck_name.replace(".inp", "")
    work.mkdir()
    inputs_dir = _stage_workdir(work, deck_name)
    res = runner.run(input_file=inputs_dir / deck_name,
                     working_dir=inputs_dir, timeout=300)
    if not res.success:
        return [ParityScore(case=f"{deck_name} (run failed)", n_paired=0,
                            slope=float("nan"), mean_abs_error=float("nan"),
                            norm_mean_error=float("nan"),
                            max_abs_error=float("nan"),
                            ref_max=0.0, cand_max=0.0)]
    scores = []
    for cand in (work / "postfiles").glob("*.PST"):
        ref = REF_PST / cand.name
        if ref.exists():
            scores.append(score_postfile_pair(ref, cand, case=cand.name))
    return scores


def _format_markdown(scores: List[ParityScore],
                     wall_time: float) -> str:
    n_total = len(scores)
    n_pass = sum(1 for s in scores if s.passes())
    n_fail = n_total - n_pass
    lines = [
        "# EPA AERMOD Test-Suite Parity Report",
        "",
        f"Generated by `scripts/run_epa_parity.py` in {wall_time:.1f}s.",
        "",
        "Pass criterion: best-fit slope of paired (reference, candidate) "
        f"concentrations within ±{DEFAULT_SLOPE_TOLERANCE} of 1.0, matching "
        "EPA's own `Compare_AERMOD_test_cases.R` published margin.",
        "",
        f"**Result: {n_pass} / {n_total} POSTFILE comparisons within tolerance.**",
        "",
        "| Case | Pass | Slope | n paired | Mean |Δ| | Ref max | Cand max |",
        "|------|:----:|------:|---------:|----------:|--------:|---------:|",
    ]
    for s in sorted(scores, key=lambda r: r.case):
        mark = "✅" if s.passes() else "❌"
        slope = f"{s.slope:.6f}" if s.slope == s.slope else "n/a"
        mae = f"{s.mean_abs_error:.4g}" if s.mean_abs_error == s.mean_abs_error else "n/a"
        lines.append(
            f"| {s.case} | {mark} | {slope} | {s.n_paired} | "
            f"{mae} | {s.ref_max:.4g} | {s.cand_max:.4g} |"
        )
    if n_fail:
        lines += ["", "## Failures", ""]
        for s in (s for s in scores if not s.passes()):
            lines.append(
                f"- **{s.case}** — slope={s.slope:.6f}, n={s.n_paired}, "
                f"mean|Δ|={s.mean_abs_error:.4g}"
            )
    return "\n".join(lines) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--output", type=Path, default=None,
                    help="Markdown report path (default: stdout)")
    ap.add_argument("--filter", default="",
                    help="Substring filter for deck names")
    ap.add_argument("--scratch", type=Path, default=None,
                    help="Scratch dir for runs (default: temp)")
    args = ap.parse_args()

    if not INPUTS.exists():
        print(f"EPA test cases not found at {EPA_DIR}", file=sys.stderr)
        return 2
    if shutil.which("aermod") is None:
        print("AERMOD binary not on PATH", file=sys.stderr)
        return 2

    decks = sorted(p.name for p in INPUTS.glob("*.inp"))
    if args.filter:
        decks = [d for d in decks if args.filter in d]
    # Skip MULTYEAR-chained decks (need shared workdir; not modeled here).
    decks = [d for d in decks
             if "MULTYEAR" not in (INPUTS / d).read_text(errors="replace").upper()]

    runner = AERMODRunner(log_level="WARNING")
    scratch = args.scratch or Path(f"/tmp/pyaermod_parity_{int(time.time())}")
    scratch.mkdir(parents=True, exist_ok=True)

    t0 = time.perf_counter()
    all_scores: List[ParityScore] = []
    for deck in decks:
        print(f"  running {deck} ...", file=sys.stderr)
        all_scores.extend(_run_one(deck, scratch, runner))
    wall = time.perf_counter() - t0

    md = _format_markdown(all_scores, wall)
    if args.output:
        args.output.write_text(md, encoding="utf-8")
        print(f"Wrote {args.output}", file=sys.stderr)
    else:
        sys.stdout.write(md)
    return 0 if all(s.passes() for s in all_scores) else 1


if __name__ == "__main__":
    sys.exit(main())
