"""
Sources tab.

Renders the project's source list as an interactive table and lets the
user add, edit, and delete any of the 10 AERMOD source types. Forms
are auto-generated by walking each dataclass's fields — this scales
across all source types without hand-writing 10 separate forms.

Field-type → widget mapping
---------------------------

==========================  ====================================
Annotation (string form)    Widget
==========================  ====================================
``str``                     ``ui.input``
``float`` / ``int``         ``ui.number``
``bool``                    ``ui.checkbox``
``Optional[<numeric>]``     ``ui.number`` with clearable
``List[Tuple[float,float]]`` text area (one ``x, y`` pair per line)
``List[str]``               text area (one entry per line)
unknown                     read-only label (escape hatch)
==========================  ====================================

Field-level defaults come from each source's ``__dataclass_fields__``
``default`` / ``default_factory``. Required fields without a default
are pre-populated with placeholder values so the new-source dialog
opens cleanly; the user must override them before save.
"""

from __future__ import annotations

import dataclasses
from typing import Any, Dict, Type

from ...input_generator import (
    AreaCircSource,
    AreaPolySource,
    AreaSource,
    BuoyLineSegment,
    BuoyLineSource,
    LineSource,
    OpenPitSource,
    PointSource,
    RLineExtSource,
    RLineSource,
    VolumeSource,
)
from .._form import emit_field, is_numeric, is_optional_numeric  # noqa: F401
from ..state import AppState

# ---------------------------------------------------------------------
# Source-type registry
# ---------------------------------------------------------------------

_SOURCE_TYPES: Dict[str, Type] = {
    "PointSource":      PointSource,
    "VolumeSource":     VolumeSource,
    "AreaSource":       AreaSource,
    "AreaCircSource":   AreaCircSource,
    "AreaPolySource":   AreaPolySource,
    "LineSource":       LineSource,
    "RLineSource":      RLineSource,
    "RLineExtSource":   RLineExtSource,
    "BuoyLineSource":   BuoyLineSource,
    "OpenPitSource":    OpenPitSource,
}


# Required-field placeholder values for new-source instantiation.
# Each value should pass __post_init__ validation so the dialog can
# open without errors; the user is expected to override before save.
_DEFAULTS: Dict[str, Any] = {
    "source_id":       "NEW_SRC",
    "x_coord":         0.0,
    "y_coord":         0.0,
    "x_start":         0.0,
    "y_start":         0.0,
    "x_end":           100.0,
    "y_end":           0.0,
    "stack_height":    10.0,
    "release_height":  2.0,
    "stack_temp":      400.0,
    "exit_velocity":   10.0,
    "stack_diameter":  1.0,
    "emission_rate":   1.0,
    "x_length":        100.0,
    "y_length":        100.0,
    "radius":          50.0,
    "vertices":        [(0.0, 0.0), (10.0, 0.0), (10.0, 10.0), (0.0, 10.0)],
    "initial_lateral_dimension":  10.0,
    "initial_vertical_dimension": 5.0,
    "init_sigma_y":               5.0,
    "init_sigma_z":               2.0,
    "pit_volume":                 1000.0,
    "pit_height":                 10.0,
    "depth":                      2.0,
    "width_top":                  20.0,
    "width_bottom":               10.0,
    "line_segments":              [
        BuoyLineSegment(
            source_id="BL_SEG1",
            x_start=0.0, y_start=0.0, x_end=100.0, y_end=0.0,
            emission_rate=1.0, release_height=2.0,
        ),
    ],
    # RLineExtSource z coords (per-endpoint elevations)
    "z_start":  0.0,
    "z_end":    0.0,
    # BuoyLineSource per-line meteorological parameters
    "avg_line_length":           100.0,
    "avg_line_width":             10.0,
    "avg_buoyancy_parameter":      5.0,
    "avg_building_height":         5.0,
    "avg_building_width":         10.0,
    "avg_building_separation":    10.0,
}


def _new_source(type_name: str) -> Any:
    """Construct a default instance of ``type_name`` for editing.

    Pulls from ``_DEFAULTS`` for every field listed there, even if the
    underlying dataclass has its own default — the GUI's defaults are
    intentionally sensible (10 m stack, 1 g/s emission) where the
    dataclass defaults to 0.
    """
    cls = _SOURCE_TYPES[type_name]
    kwargs = {}
    for f in dataclasses.fields(cls):
        if f.name in _DEFAULTS:
            kwargs[f.name] = _DEFAULTS[f.name]
    return cls(**kwargs)


def _summary_row(src: Any) -> Dict[str, Any]:
    """Compact dict suitable for AG-Grid display."""
    cls_name = type(src).__name__
    if hasattr(src, "x_coord"):
        x, y = src.x_coord, src.y_coord
    elif hasattr(src, "x_start"):
        x, y = src.x_start, src.y_start
    elif hasattr(src, "vertices") and src.vertices:
        x, y = src.vertices[0]
    elif (getattr(src, "line_segments", None)
          and getattr(src.line_segments[0], "x_start", None) is not None):
        # BuoyLineSource: summarise from the first buoyant line segment
        x, y = src.line_segments[0].x_start, src.line_segments[0].y_start
    else:
        x, y = "", ""
    return {
        "id": src.source_id,
        "type": cls_name,
        "x": x,
        "y": y,
        "Q (g/s)": getattr(src, "emission_rate", ""),
    }


# ---------------------------------------------------------------------
# Page render
# ---------------------------------------------------------------------

def render(state: AppState) -> None:
    """Render the Sources tab."""
    from nicegui import ui

    table_ref = {"obj": None}

    def _refresh_table():
        rows = [_summary_row(s) for s in state.project.sources.sources]
        if table_ref["obj"] is not None:
            table_ref["obj"].rows[:] = rows
            table_ref["obj"].update()

    # ----- header -----------------------------------------------------
    with ui.row().classes("items-center q-gutter-md"):
        ui.label("Sources").classes("text-h6")
        type_select = ui.select(
            options=list(_SOURCE_TYPES.keys()),
            label="Type",
            value="PointSource",
        ).classes("w-48")

        def _on_add():
            new_src = _new_source(type_select.value)
            state.project.sources.sources.append(new_src)
            state.mark_dirty()
            _refresh_table()
            _open_editor(new_src)

        ui.button("Add", on_click=_on_add).props("color=primary")

    ui.separator().classes("q-my-md")

    # ----- table ------------------------------------------------------
    columns = [
        {"name": "id", "label": "ID", "field": "id", "align": "left"},
        {"name": "type", "label": "Type", "field": "type", "align": "left"},
        {"name": "x", "label": "X", "field": "x", "align": "right"},
        {"name": "y", "label": "Y", "field": "y", "align": "right"},
        {"name": "Q (g/s)", "label": "Q (g/s)", "field": "Q (g/s)",
         "align": "right"},
    ]
    rows = [_summary_row(s) for s in state.project.sources.sources]
    table = ui.table(columns=columns, rows=rows, row_key="id").classes(
        "w-full"
    )
    table_ref["obj"] = table

    # Add edit / delete column via slot
    table.add_slot(
        "body-cell-id",
        '''
        <q-td :props="props">
          <q-btn dense flat icon="edit"
                 @click="$parent.$emit(`edit`, props.row.id)" />
          <q-btn dense flat icon="delete" color="negative"
                 @click="$parent.$emit(`delete`, props.row.id)" />
          {{ props.row.id }}
        </q-td>
        ''',
    )

    def _open_editor(src: Any) -> None:
        with ui.dialog() as dialog, ui.card().classes("min-w-[600px]"):
            ui.label(f"Edit {type(src).__name__} — {src.source_id}").classes(
                "text-h6"
            )
            with ui.column().classes("w-full q-gutter-sm"):
                for fmeta in dataclasses.fields(src):
                    emit_field(ui.row().classes("w-full"), src, fmeta)
            with ui.row().classes("justify-end q-gutter-sm q-mt-md"):
                ui.button("Close", on_click=dialog.close).props("flat")
                def _on_save():
                    state.mark_dirty()
                    _refresh_table()
                    dialog.close()
                ui.button("Save", on_click=_on_save).props("color=primary")
        dialog.open()

    def _find_by_id(sid: str):
        for s in state.project.sources.sources:
            if s.source_id == sid:
                return s
        return None

    table.on("edit", lambda e: _open_editor(_find_by_id(e.args)))

    def _on_delete(e):
        sid = e.args
        state.project.sources.sources[:] = [
            s for s in state.project.sources.sources if s.source_id != sid
        ]
        state.mark_dirty()
        _refresh_table()
        ui.notify(f"Deleted {sid}", color="warning")

    table.on("delete", _on_delete)

    if not rows:
        ui.label("No sources yet. Add one above.").classes(
            "text-grey q-mt-sm"
        )


__all__ = ["render"]
